# Spark defaults
spark.master                       yarn
spark.submit.deployMode            client
spark.eventLog.enabled             true
spark.eventLog.dir                 hdfs://namenode:9000/spark-events
spark.history.fs.logDirectory      hdfs://namenode:9000/spark-events
spark.sql.warehouse.dir            hdfs://namenode:9000/user/hive/warehouse
spark.sql.catalogImplementation    hive
spark.hadoop.fs.defaultFS          hdfs://namenode:9000
spark.hadoop.yarn.resourcemanager.address namenode:8032
spark.yarn.historyServer.address   spark-history:18080
spark.executor.extraJavaOptions    -Dlog4j.configuration=file:/opt/spark/conf/log4j.properties

# OpenLineage (Marquez) integration
# JAR СѓР¶Рµ РІРєР»СЋС‡С‘РЅ РІ РѕР±СЂР°Р·: /opt/spark/jars/openlineage-spark_2.13-1.21.0.jar
spark.extraListeners                 io.openlineage.spark.agent.OpenLineageSparkListener
spark.openlineage.namespace          hadoop-cluster
# РСЃРїРѕР»СЊР·СѓРµРј HTTP С‚СЂР°РЅСЃРїРѕСЂС‚ РІ Marquez API
spark.openlineage.transport.type     http
spark.openlineage.transport.url      http://marquez:5000

