# Spark defaults
spark.master                       yarn
spark.submit.deployMode            client
spark.eventLog.enabled             true
spark.eventLog.dir                 hdfs://namenode:9000/spark-events
spark.history.fs.logDirectory      hdfs://namenode:9000/spark-events
spark.sql.warehouse.dir            hdfs://namenode:9000/opt/hive/warehouse
spark.hadoop.fs.defaultFS          hdfs://namenode:9000
spark.hadoop.yarn.resourcemanager.address namenode:8032
spark.yarn.historyServer.address   datanode:18080
spark.executor.extraJavaOptions    -Dlog4j.configuration=file:/opt/spark/conf/log4j.properties

