kyuubi.frontend.bind.host 0.0.0.0
kyuubi.frontend.protocols THRIFT_BINARY
kyuubi.frontend.thrift.binary.bind.port 10009

kyuubi.engine.type SPARK_SQL
kyuubi.engine.share.level USER

kyuubi.ha.enabled false

spark.master yarn
spark.submit.deployMode client
spark.yarn.historyServer.address datanode:18080
spark.eventLog.enabled true
spark.eventLog.dir hdfs://namenode:9000/spark-events
spark.history.fs.logDirectory hdfs://namenode:9000/spark-events
spark.sql.warehouse.dir hdfs://namenode:9000/opt/hive/warehouse

